### ISSUE TITLE
binarys and git readme don't match. 

### ISSUE THREAD

**Issue by mark-a-s** [akarki15/dbdot#17]
usage of the binary
Usage of ./dbdot-darwin-amd64:
  -dbname string
    	dbname for which you want to generate dot file
  -sslmode
    	enable sslmode for postgres db connection
  -user string
    	username of postgres db
  -whitelist string
    	comma separated list of tables you want to generate dot file for

however the readme / github says it supports the following flags.

 -W    ask for password
  -dbname string
        dbname for which you want to generate dot file
  -host string
        database host (default "localhost")
  -port uint
        database port (default 5432)
  -schema string
        schema name (default "public")
  -sslmode
        enable sslmode for postgres db connection
  -user string
        username of postgres db
  -whitelist string
        comma separated list of tables you want to generate dot file for

**e.g. if you try and use the binaries found on 'latest releases' you can't use -schema,-port, -host, -W,**

**Comment by turulomio** [comment]
I have the same problem. Could you update binary release or can give compilation instructions. Thank you :)

**Comment by akarki15** [comment]
Sorry for the long delay! Caught up in job- I have updated the binaries :)

I will be adding compilation instructions. If I have time, I also want to add automated builds: https://github.com/akarki15/dbdot/issues/18

**Comment by akarki15** [comment]
New binary:


```
aashishkarki@aashishkarkis-MacBook-Air release % ./dbdot-darwin-amd64 --help                     
Usage of ./dbdot-darwin-amd64:
  -W	ask for password
  -dbname string
    	dbname for which you want to generate dot file
  -host string
    	database host (default "localhost")
  -port uint
    	database port (default 5432)
  -schema string
    	schema name (default "public")
  -sslmode
    	enable sslmode for postgres db connection
  -user string
    	username of postgres db
  -whitelist string
    	comma separated list of tables you want to generate dot file for
```
